create table Accounts
(
	Id INT PRIMARY KEY IDENTITY(1, 1),

	Email VARCHAR(50) NOT NULL,
	Password VARCHAR(50) NOT NULL,

	Name VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	Nickname VARCHAR(50) NOT NULL,
	Tel VARCHAR(20) NOT NULL,
	
	Gender VARCHAR(20) NOT NULL,
	Level VARCHAR(20) NOT NULL,
	
	BirthDate DATE NOT NULL
)
go

create table Articles
(
	Id INT PRIMARY KEY IDENTITY(1, 1),
	CreatorId INT DEFAULT(0) NOT NULL FOREIGN KEY REFERENCES Accounts(Id)
		ON DELETE SET DEFAULT ON UPDATE CASCADE,

	Type VARCHAR(20) NOT NULL,
	Title VARCHAR(100) NOT NULL,
	Description TEXT NOT NULL,

	FirstDate DATETIME NOT NULL,
	LastDate DATETIME NOT NULL,

	ImageUrl VARCHAR(50) NOT NULL,
	ImageColorHex VARCHAR(10) NOT NULL
)
go